author: "Hermann Mayer <hermann.mayer92@gmail.com>"
category: "admin"
summary: "Allows users to acknowledge unread messages"
home: "https://github.com/hausgold/ejabberd-unread"
url: "git@github.com:hausgold/ejabberd-unread.git"
